project_id = "eedtqzfatasqkakhyuua"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.web-search]
verify_jwt = false

[functions.map-search]
verify_jwt = false
